<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Food;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $foods = [
            [
                'nama_makanan' => 'Oatmeal dengan Blueberry',
                'deskripsi' => 'Oatmeal dimasak dengan air, ditaburi blueberry segar',
                'kategori_makanan' => 'pagi',
                'kalori' => 150,
                'protein' => 5.0,
                'karbohidrat' => 27.0,
                'lemak' => 2.5,
            ],
            [
                'nama_makanan' => 'Telur Dadar 3 Putih Telur',
                'deskripsi' => '3 putih telur dengan sedikit minyak zaitun',
                'kategori_makanan' => 'pagi',
                'kalori' => 51,
                'protein' => 11.0,
                'karbohidrat' => 0.7,
                'lemak' => 0.2,
            ],
            [
                'nama_makanan' => 'Greek Yogurt dengan Almond',
                'deskripsi' => 'Greek yogurt rendah lemak dengan 10 butir almond',
                'kategori_makanan' => 'pagi',
                'kalori' => 180,
                'protein' => 15.0,
                'karbohidrat' => 9.0,
                'lemak' => 9.0,
            ],
            [
                'nama_makanan' => 'Roti Gandum dengan Alpukat',
                'deskripsi' => '2 lembar roti gandum dengan 1/4 alpukat',
                'kategori_makanan' => 'pagi',
                'kalori' => 250,
                'protein' => 8.0,
                'karbohidrat' => 30.0,
                'lemak' => 12.0,
            ],
            [
                'nama_makanan' => 'Smoothie Protein',
                'deskripsi' => 'Whey protein, pisang, dan bayam',
                'kategori_makanan' => 'pagi',
                'kalori' => 220,
                'protein' => 25.0,
                'karbohidrat' => 20.0,
                'lemak' => 3.0,
            ],
            [
                'nama_makanan' => 'Quinoa Bowl',
                'deskripsi' => 'Quinoa dengan irisan apel dan kayu manis',
                'kategori_makanan' => 'pagi',
                'kalori' => 210,
                'protein' => 8.0,
                'karbohidrat' => 40.0,
                'lemak' => 3.0,
            ],
            [
                'nama_makanan' => 'Pancake Protein',
                'deskripsi' => 'Pancake dari tepung oat dan whey protein',
                'kategori_makanan' => 'pagi',
                'kalori' => 280,
                'protein' => 22.0,
                'karbohidrat' => 35.0,
                'lemak' => 5.0,
            ],
            [
                'nama_makanan' => 'Keju Cottage dengan Buah',
                'deskripsi' => 'Keju cottage rendah lemak dengan stroberi',
                'kategori_makanan' => 'pagi',
                'kalori' => 160,
                'protein' => 20.0,
                'karbohidrat' => 12.0,
                'lemak' => 3.0,
            ],
            [
                'nama_makanan' => 'Dada Ayam Grill dengan Brokoli',
                'deskripsi' => '150g dada ayam tanpa kulit dengan 100g brokoli kukus',
                'kategori_makanan' => 'siang',
                'kalori' => 280,
                'protein' => 42.0,
                'karbohidrat' => 7.0,
                'lemak' => 8.0,
            ],
            [
                'nama_makanan' => 'Salmon dengan Asparagus',
                'deskripsi' => '150g salmon panggang dengan asparagus',
                'kategori_makanan' => 'siang',
                'kalori' => 320,
                'protein' => 34.0,
                'karbohidrat' => 5.0,
                'lemak' => 18.0,
            ],
            [
                'nama_makanan' => 'Nasi Merah dengan Tahu dan Sayuran',
                'deskripsi' => '100g nasi merah, 150g tahu, campuran sayuran',
                'kategori_makanan' => 'siang',
                'kalori' => 350,
                'protein' => 20.0,
                'karbohidrat' => 45.0,
                'lemak' => 10.0,
            ],
            [
                'nama_makanan' => 'Salad Ayam dengan Dressing Lemon',
                'deskripsi' => 'Salad hijau dengan dada ayam suwir dan dressing lemon',
                'kategori_makanan' => 'siang',
                'kalori' => 300,
                'protein' => 35.0,
                'karbohidrat' => 10.0,
                'lemak' => 12.0,
            ],
            [
                'nama_makanan' => 'Tuna Sandwich Whole Wheat',
                'deskripsi' => 'Roti gandum dengan tuna dan selada',
                'kategori_makanan' => 'siang',
                'kalori' => 320,
                'protein' => 28.0,
                'karbohidrat' => 35.0,
                'lemak' => 8.0,
            ],
            [
                'nama_makanan' => 'Quinoa Salad dengan Chickpea',
                'deskripsi' => 'Quinoa, chickpea, tomat, mentimun, dan lemon',
                'kategori_makanan' => 'siang',
                'kalori' => 290,
                'protein' => 12.0,
                'karbohidrat' => 45.0,
                'lemak' => 7.0,
            ],
            [
                'nama_makanan' => 'Ikan Dori dengan Kembang Kol',
                'deskripsi' => '150g ikan dori panggang dengan puree kembang kol',
                'kategori_makanan' => 'siang',
                'kalori' => 270,
                'protein' => 30.0,
                'karbohidrat' => 8.0,
                'lemak' => 12.0,
            ],
            [
                'nama_makanan' => 'Burger Daging Sapi Lean',
                'deskripsi' => 'Burger dari daging sapi lean tanpa roti, dengan salad',
                'kategori_makanan' => 'siang',
                'kalori' => 310,
                'protein' => 38.0,
                'karbohidrat' => 5.0,
                'lemak' => 15.0,
            ],
            [
                'nama_makanan' => 'Protein Bar',
                'deskripsi' => 'Protein bar rendah gula',
                'kategori_makanan' => 'sore',
                'kalori' => 200,
                'protein' => 20.0,
                'karbohidrat' => 15.0,
                'lemak' => 6.0,
            ],
            [
                'nama_makanan' => 'Almond 20 Butir',
                'deskripsi' => 'Kacang almond mentah',
                'kategori_makanan' => 'sore',
                'kalori' => 160,
                'protein' => 6.0,
                'karbohidrat' => 6.0,
                'lemak' => 14.0,
            ],
            [
                'nama_makanan' => 'Apel dengan Selai Kacang',
                'deskripsi' => '1 buah apel dengan 1 sendok selai kacang',
                'kategori_makanan' => 'sore',
                'kalori' => 190,
                'protein' => 4.0,
                'karbohidrat' => 25.0,
                'lemak' => 8.0,
            ],
            [
                'nama_makanan' => 'Edamame Rebus',
                'deskripsi' => '100g edamame rebus dengan sedikit garam',
                'kategori_makanan' => 'sore',
                'kalori' => 120,
                'protein' => 11.0,
                'karbohidrat' => 9.0,
                'lemak' => 5.0,
            ],
            [
                'nama_makanan' => 'Greek Yogurt',
                'deskripsi' => '150g Greek yogurt plain rendah lemak',
                'kategori_makanan' => 'sore',
                'kalori' => 90,
                'protein' => 15.0,
                'karbohidrat' => 6.0,
                'lemak' => 0.5,
            ],
            [
                'nama_makanan' => 'Telur Rebus',
                'deskripsi' => '2 butir telur rebus',
                'kategori_makanan' => 'sore',
                'kalori' => 156,
                'protein' => 12.6,
                'karbohidrat' => 1.2,
                'lemak' => 10.6,
            ],
            [
                'nama_makanan' => 'Protein Shake',
                'deskripsi' => '1 scoop whey protein dengan air',
                'kategori_makanan' => 'sore',
                'kalori' => 120,
                'protein' => 24.0,
                'karbohidrat' => 3.0,
                'lemak' => 1.5,
            ],
            [
                'nama_makanan' => 'Daging Sapi Lean dengan Bayam',
                'deskripsi' => '150g daging sapi lean panggang dengan bayam tumis',
                'kategori_makanan' => 'malam',
                'kalori' => 290,
                'protein' => 40.0,
                'karbohidrat' => 6.0,
                'lemak' => 12.0,
            ],
            [
                'nama_makanan' => 'Ikan Kembung Bakar',
                'deskripsi' => '200g ikan kembung bakar dengan sambal tomat',
                'kategori_makanan' => 'malam',
                'kalori' => 260,
                'protein' => 32.0,
                'karbohidrat' => 2.0,
                'lemak' => 14.0,
            ],
            [
                'nama_makanan' => 'Ayam Kukus dengan Jamur',
                'deskripsi' => '150g dada ayam kukus dengan tumisan jamur',
                'kategori_makanan' => 'malam',
                'kalori' => 230,
                'protein' => 38.0,
                'karbohidrat' => 5.0,
                'lemak' => 6.0,
            ],
            [
                'nama_makanan' => 'Tempe Panggang dengan Lalapan',
                'deskripsi' => '150g tempe panggang dengan lalapan segar',
                'kategori_makanan' => 'malam',
                'kalori' => 250,
                'protein' => 20.0,
                'karbohidrat' => 15.0,
                'lemak' => 12.0,
            ],
            [
                'nama_makanan' => 'Sup Ayam dan Sayuran',
                'deskripsi' => 'Sup dengan dada ayam, wortel, brokoli, dan jamur',
                'kategori_makanan' => 'malam',
                'kalori' => 200,
                'protein' => 25.0,
                'karbohidrat' => 10.0,
                'lemak' => 6.0,
            ],
            [
                'nama_makanan' => 'Udang Saus Tiram',
                'deskripsi' => '150g udang tumis dengan sedikit saus tiram dan sayuran',
                'kategori_makanan' => 'malam',
                'kalori' => 220,
                'protein' => 28.0,
                'karbohidrat' => 8.0,
                'lemak' => 8.0,
            ],
            [
                'nama_makanan' => 'Omelet Sayuran',
                'deskripsi' => '3 putih telur dengan paprika, tomat, dan bawang',
                'kategori_makanan' => 'malam',
                'kalori' => 180,
                'protein' => 18.0,
                'karbohidrat' => 10.0,
                'lemak' => 7.0,
            ],
        ];

        foreach ($foods as $food) {
            Food::create($food);
        }
    }
}